// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheBlock.Infrastructure;

#nullable disable

namespace TheBlock.Migrations.Sqlite
{
    [DbContext(typeof(YardDbContext))]
    [Migration("20260903053709_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("TheBlock.Infrastructure.BidRow", b =>
                {
                    b.Property<string>("VehicleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AtMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BidCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WonBuyNow")
                        .HasColumnType("INTEGER");

                    b.HasKey("VehicleId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("TheBlock.Infrastructure.PhotoRow", b =>
                {
                    b.Property<string>("File")
                        .HasColumnType("TEXT");

                    b.Property<int>("Seq")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("File");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("TheBlock.Infrastructure.VehicleRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuctionStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BidCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BuyNowPrice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ConditionGrade")
                        .HasColumnType("REAL");

                    b.Property<string>("ConditionReport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentBid")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("DamageNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Drivetrain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExteriorColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Images")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InteriorColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OdometerKm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReservePrice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SellingDealership")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Seq")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartingBid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitleStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Trim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Seq")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
